### ISSUE TITLE
Segmentation fault on 64-bit Linux

### ISSUE THREAD

**Issue by M-HT** [ptitSeb/freespace2#1]
The program crashes on 64-bit Linux during mission briefing when playing Freespace 1.

The problem is in class Timer in file src/sound/audiostr-openal.cpp. The fix is to change the datatype of attribute m_dwUser from DWORD to ptr_u in line 157 and the same for parameter dwUser in method Create in lines 153 and 288.

**Comment by ptitSeb** [comment]
Oh, thanks. I'll fix that and try to do some some testing on 64bits Linux.

**Comment by ptitSeb** [comment]
Ok, I've pushed the fix. Thanks again for the full debugging and fixing :)
